version: '3.1'

services:
  postgres:
    image: postgres:15.8
    # see https://www.postgresql.org/docs/current/non-durability.html
    # see https://github.com/testjavascript/nodejs-integration-tests-best-practices/blob/master/example-application/test/docker-compose.yml
    command: '-c full_page_writes=off -c fsync=off -c synchronous_commit=off'
    ports:
      - '25532:5432'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
  waitpostgres:
    image: postgres:15.8
    links:
      - postgres
    depends_on:
      - postgres
    entrypoint:
      - bash
      - -c
      - 'until /usr/local/bin/psql postgres://test:test@postgres/test -c "SELECT 1"; do sleep 5; done'
